[package]
name = "sel4-apps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build]
target = "x86_64-apple-darwin"

[profile.dev]
panic = "abort"
